language: python
python:
    - "2.7"
install: 
    - "pip install pep8"
    - "pip install pylint"
    - "pip install coverage"
    - "pip install coveralls"
script: 
    - "./setup check"
after_success:
    coveralls
