# pylint: disable=wildcard-import
from virtTrinity.providers.virsh_cmd.picker.command import *
from virtTrinity.providers.virsh_cmd.picker.cmds import *
from virtTrinity.providers.virsh_cmd.picker.optset import *

from virtTrinity.providers.virsh_cmd.picker.cmd_restore import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domfsfreeze import *
from virtTrinity.providers.virsh_cmd.picker.cmd_find_storage_pool_sources import *
from virtTrinity.providers.virsh_cmd.picker.cmd_qemu_attach import *
from virtTrinity.providers.virsh_cmd.picker.cmd_numatune import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domjobabort import *
from virtTrinity.providers.virsh_cmd.picker.cmd_save_image_dumpxml import *
from virtTrinity.providers.virsh_cmd.picker.cmd_snapshot_list import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domxml_from_native import *
from virtTrinity.providers.virsh_cmd.picker.cmd_reboot import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_info import *
from virtTrinity.providers.virsh_cmd.picker.cmd_suspend import *
from virtTrinity.providers.virsh_cmd.picker.cmd_snapshot_revert import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_refresh import *
from virtTrinity.providers.virsh_cmd.picker.cmd_help import *
from virtTrinity.providers.virsh_cmd.picker.cmd_console import *
from virtTrinity.providers.virsh_cmd.picker.cmd_managedsave import *
from virtTrinity.providers.virsh_cmd.picker.cmd_change_media import *
from virtTrinity.providers.virsh_cmd.picker.cmd_emulatorpin import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domif_setlink import *
from virtTrinity.providers.virsh_cmd.picker.cmd_autostart import *
from virtTrinity.providers.virsh_cmd.picker.cmd_managedsave_remove import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domfsinfo import *
from virtTrinity.providers.virsh_cmd.picker.cmd_qemu_monitor_command import *
from virtTrinity.providers.virsh_cmd.picker.cmd_save import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_create_as import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nodedev_list import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_name import *
from virtTrinity.providers.virsh_cmd.picker.cmd_iface_name import *
from virtTrinity.providers.virsh_cmd.picker.cmd_migrate_setspeed import *
from virtTrinity.providers.virsh_cmd.picker.cmd_blkdeviotune import *
from virtTrinity.providers.virsh_cmd.picker.cmd_attach_disk import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_clone import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nodesuspend import *
from virtTrinity.providers.virsh_cmd.picker.cmd_blockjob import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domifstat import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_uuid import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_autostart import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domuuid import *
from virtTrinity.providers.virsh_cmd.picker.cmd_dommemstat import *
from virtTrinity.providers.virsh_cmd.picker.cmd_snapshot_current import *
from virtTrinity.providers.virsh_cmd.picker.cmd_desc import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vcpucount import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domcontrol import *
from virtTrinity.providers.virsh_cmd.picker.cmd_ttyconsole import *
from virtTrinity.providers.virsh_cmd.picker.cmd_edit import *
from virtTrinity.providers.virsh_cmd.picker.cmd_freecell import *
from virtTrinity.providers.virsh_cmd.picker.cmd_cpu_stats import *
from virtTrinity.providers.virsh_cmd.picker.cmd_secret_set_value import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vcpuinfo import *
from virtTrinity.providers.virsh_cmd.picker.cmd_metadata import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domblkstat import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_edit import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domstate import *
from virtTrinity.providers.virsh_cmd.picker.cmd_dump import *
from virtTrinity.providers.virsh_cmd.picker.cmd_send_key import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_resize import *
from virtTrinity.providers.virsh_cmd.picker.cmd_node_memory_tune import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_update import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domstats import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_build import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domiflist import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_name import *
from virtTrinity.providers.virsh_cmd.picker.cmd_event import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_undefine import *
from virtTrinity.providers.virsh_cmd.picker.cmd_dompmwakeup import *
from virtTrinity.providers.virsh_cmd.picker.cmd_iothreadinfo import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_start import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_create import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domfstrim import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domblklist import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_wipe import *
from virtTrinity.providers.virsh_cmd.picker.cmd_cd import *
from virtTrinity.providers.virsh_cmd.picker.cmd_iface_bridge import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vcpupin import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_path import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_create import *
from virtTrinity.providers.virsh_cmd.picker.cmd_freepages import *
from virtTrinity.providers.virsh_cmd.picker.cmd_dompmsuspend import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nwfilter_define import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domjobinfo import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domhostname import *
from virtTrinity.providers.virsh_cmd.picker.cmd_resume import *
from virtTrinity.providers.virsh_cmd.picker.cmd_setmem import *
from virtTrinity.providers.virsh_cmd.picker.cmd_blockpull import *
from virtTrinity.providers.virsh_cmd.picker.cmd_inject_nmi import *
from virtTrinity.providers.virsh_cmd.picker.cmd_save_image_edit import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_define import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_undefine import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_destroy import *
from virtTrinity.providers.virsh_cmd.picker.cmd_iface_unbridge import *
from virtTrinity.providers.virsh_cmd.picker.cmd_detach_disk import *
from virtTrinity.providers.virsh_cmd.picker.cmd_blockcommit import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domfsthaw import *
from virtTrinity.providers.virsh_cmd.picker.cmd_iothreadpin import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_autostart import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nodedev_detach import *
from virtTrinity.providers.virsh_cmd.picker.cmd_memtune import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_event import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nodedev_reattach import *
from virtTrinity.providers.virsh_cmd.picker.cmd_detach_device import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_dumpxml import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_upload import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nodecpustats import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_define_as import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domcapabilities import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_download import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nodedev_dumpxml import *
from virtTrinity.providers.virsh_cmd.picker.cmd_echo import *
from virtTrinity.providers.virsh_cmd.picker.cmd_secret_undefine import *
from virtTrinity.providers.virsh_cmd.picker.cmd_cpu_models import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_dumpxml import *
from virtTrinity.providers.virsh_cmd.picker.cmd_secret_define import *
from virtTrinity.providers.virsh_cmd.picker.cmd_shutdown import *
from virtTrinity.providers.virsh_cmd.picker.cmd_send_process_signal import *
from virtTrinity.providers.virsh_cmd.picker.cmd_qemu_agent_command import *
from virtTrinity.providers.virsh_cmd.picker.cmd_schedinfo import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nwfilter_dumpxml import *
from virtTrinity.providers.virsh_cmd.picker.cmd_cpu_compare import *
from virtTrinity.providers.virsh_cmd.picker.cmd_create import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nwfilter_edit import *
from virtTrinity.providers.virsh_cmd.picker.cmd_iface_define import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domifaddr import *
from virtTrinity.providers.virsh_cmd.picker.cmd_maxvcpus import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_create import *
from virtTrinity.providers.virsh_cmd.picker.cmd_secret_dumpxml import *
from virtTrinity.providers.virsh_cmd.picker.cmd_start import *
from virtTrinity.providers.virsh_cmd.picker.cmd_define import *
from virtTrinity.providers.virsh_cmd.picker.cmd_blockcopy import *
from virtTrinity.providers.virsh_cmd.picker.cmd_find_storage_pool_sources_as import *
from virtTrinity.providers.virsh_cmd.picker.cmd_qemu_monitor_event import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domtime import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vncdisplay import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nodedev_destroy import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_info import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_list import *
from virtTrinity.providers.virsh_cmd.picker.cmd_migrate_getspeed import *
from virtTrinity.providers.virsh_cmd.picker.cmd_allocpages import *
from virtTrinity.providers.virsh_cmd.picker.cmd_reset import *
from virtTrinity.providers.virsh_cmd.picker.cmd_snapshot_create import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_key import *
from virtTrinity.providers.virsh_cmd.picker.cmd_lxc_enter_namespace import *
from virtTrinity.providers.virsh_cmd.picker.cmd_secret_get_value import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domdisplay import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nwfilter_undefine import *
from virtTrinity.providers.virsh_cmd.picker.cmd_snapshot_parent import *
from virtTrinity.providers.virsh_cmd.picker.cmd_detach_interface import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domblkinfo import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domif_getlink import *
from virtTrinity.providers.virsh_cmd.picker.cmd_iface_edit import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_delete import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_edit import *
from virtTrinity.providers.virsh_cmd.picker.cmd_migrate import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domxml_to_native import *
from virtTrinity.providers.virsh_cmd.picker.cmd_snapshot_info import *
from virtTrinity.providers.virsh_cmd.picker.cmd_dumpxml import *
from virtTrinity.providers.virsh_cmd.picker.cmd_iface_start import *
from virtTrinity.providers.virsh_cmd.picker.cmd_snapshot_delete import *
from virtTrinity.providers.virsh_cmd.picker.cmd_save_image_define import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_name import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domiftune import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_destroy import *
from virtTrinity.providers.virsh_cmd.picker.cmd_iface_undefine import *
from virtTrinity.providers.virsh_cmd.picker.cmd_update_device import *
from virtTrinity.providers.virsh_cmd.picker.cmd_snapshot_create_as import *
from virtTrinity.providers.virsh_cmd.picker.cmd_blkiotune import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_define import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_uuid import *
from virtTrinity.providers.virsh_cmd.picker.cmd_migrate_compcache import *
from virtTrinity.providers.virsh_cmd.picker.cmd_destroy import *
from virtTrinity.providers.virsh_cmd.picker.cmd_cpu_baseline import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_create_as import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_delete import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_dumpxml import *
from virtTrinity.providers.virsh_cmd.picker.cmd_connect import *
from virtTrinity.providers.virsh_cmd.picker.cmd_screenshot import *
from virtTrinity.providers.virsh_cmd.picker.cmd_iface_dumpxml import *
from virtTrinity.providers.virsh_cmd.picker.cmd_net_dhcp_leases import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_info import *
from virtTrinity.providers.virsh_cmd.picker.cmd_undefine import *
from virtTrinity.providers.virsh_cmd.picker.cmd_setmaxmem import *
from virtTrinity.providers.virsh_cmd.picker.cmd_attach_interface import *
from virtTrinity.providers.virsh_cmd.picker.cmd_snapshot_dumpxml import *
from virtTrinity.providers.virsh_cmd.picker.cmd_attach_device import *
from virtTrinity.providers.virsh_cmd.picker.cmd_snapshot_edit import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_pool import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_start import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nodedev_create import *
from virtTrinity.providers.virsh_cmd.picker.cmd_vol_create_from import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domname import *
from virtTrinity.providers.virsh_cmd.picker.cmd_dominfo import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nodedev_reset import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domid import *
from virtTrinity.providers.virsh_cmd.picker.cmd_nodememstats import *
from virtTrinity.providers.virsh_cmd.picker.cmd_iface_destroy import *
from virtTrinity.providers.virsh_cmd.picker.cmd_migrate_setmaxdowntime import *
from virtTrinity.providers.virsh_cmd.picker.cmd_blockresize import *
from virtTrinity.providers.virsh_cmd.picker.cmd_iface_mac import *
from virtTrinity.providers.virsh_cmd.picker.cmd_domblkerror import *
from virtTrinity.providers.virsh_cmd.picker.cmd_pool_list import *
from virtTrinity.providers.virsh_cmd.picker.cmd_setvcpus import *

from virtTrinity.providers.virsh_cmd.picker.dom_xml import *

root_picker = 'CmdPicker'
